# Diskussion 

In dieser Arbeit wurde der Einfluss von Landnutzung und Urbanisierung auf hohlraumnistende Wildbienen und deren Gegenspieler untersucht. Es wurden die vorkommenden Arten, Artenzahl und Abundanz der Wildbienen und die Artenzahl der natürlichen Gegenspieler als auch die Abundanz der häufigsten Bienenart, der Rostroten Mauerbiene (*Osmia bicornis*) aus Nisthilfen analysiert. Die 259 Nisthilfen waren im Jahr 2019 an Standorten über ganz Deutschland verteilt ausgehängt. Landnutzung und Urbanisierungsgrad wurden anhand von frei verfügbaren Satellitendaten bewertet. Die Landnutzung wurde durch zwei Parameter der Landschaftsstruktur und durch den Anteil verschiedener Landnutzungsformen beschrieben, der Urbanisierungsgrad wurde durch den Anteil an versiegelter Fläche im Umkreis der Nisthilfenstandorte beschrieben. Des Weiteren wurde der Einfluss von bereits vorhandenen Insektenhäusern am Nisthilfenstandort und der Einfluss von Klimavariablen mituntersucht, um diese Einflüsse von den oben genannten abzugrenzen und um die Modellierungen zu verbessern.      
Folgende Zusammenhänge konnten in dieser Arbeit erfasst werden:

- Die Artenzahl der Wildbienen wird positiv von vorhandenen Insektenhäusern in der Umgebung des Nisthilfenstandortes beeinflusst und ist maximal bei einem mittelerem Versiegelungsgrad von 30% versiegelter Fläche im 1000m-Radius
- Die Abundanz der Wildbienen ist maximal bei einem mittlerem Versiegelungsgrad von 25% versiegelter Fläche im 500m-Radius und wird zudem positiv von der Anzahl an Landnutzungsklassen im 500m-Radius beeinflusst.
- Die Artenzahl der natürlichen Gegenspieler konnte nur durch die Artenzahl der Wirte beschrieben werden. Es konnte kein zusätzlicher Einfluss von Versiegelungsgrad oder Landschaftskomplexität augezeigt werden.
- Die Abundanz von *Osmia bicornis* ist bei einem mittlerem Versiegelungsgrad von 35% versiegelter Fläche im 500m-Radius maximal und wird zudem negativ vom Anteil der Ackerlandfläche im 500m-Radius beeinflusst und nimmt innerhalb Deutschlands nach Norden hin zu.
- Ein Zusammenhang zwischen dem Urbanisierungsgrad und der Artengemeinschaft oder den Wirt-Parasitoid-Interaktionen in den Nisthilfen kann in dieser Arbeit nicht aufgezeigt werden.


Es konnten insgesamt 27 Wirts-Bienenarten sowie als Parasitoide fünf Kuckucksbienenarten und neun parasitische Wespenarten nachgewiesen werden. Die Vermutung, dass im artenreichen Stadtrandbereich durch die Nisthilfen des Schulinsektenhaus-Projektes mehr Arten erfasst werden können als in der Studie von @tscharntke1998 hat sich nicht bestätigt. Zwar wurden sieben Arten erfasst, die in der genannten Studie nicht nachgewiesen wurden, diesen sieben Arten stehen jedoch zwölf Arten gegenüber, die in den Nisthilfen dieser Arbeit nicht vorkamen.   
Da zwischen den beiden Studien über 20 Jahre liegen, ist eine generelle Veränderung der in Deutschland vorkommenden Arten und ihrer Häufigkeit in Nisthilfen möglich, was eine Ursache dafür sein könnte, dass in der Arbeit von @tscharntke1998 zwölf Arten nachgewiesen wurden, die in dieser Arbeit nicht beschrieben wurden. Aufschluss darüber könnte der Vergleich mit weiteren Studien zu Nisthilfen in Deutschland geben. So wurden elf von den zwölf Arten auch nicht in der Studie von @pereira-peixoto2014 beschrieben, welche wie diese Arbeit den Stadt-Land-Gradienten untersuchte. Nimmt man die im Gründland durchgeführte Studie von @steckel2014 vergleichend hinzu, so bleiben von den durch  @tscharntke1998 nachgewiesenen Arten nur fünf Arten, darunter vier Arten der Gattung *Hylaeus*, die nicht in einer der neueren Studien beschrieben wurden. Es ist nicht auszuschließen, dass bei der Bestimmung der *Hylaeus*-Arten in dieser Arbeit Fehlbestimmungen vorkamen, denn die Artbestimmung der Gattung *Hylaeus* ist anspruchsvoll. Daher sollte beim Vergleich mit den anderen Studien hier eine geringe Unsicherheit der Daten beachtet werden,  was insbesondere für die Artengruppe *Hylaeus gibbus* gilt [@straka2011].  
Durch den Vergleich der Studie von @tscharntke1998 mit Studien neueren Datums kann der Effekt von generellen Veränderungen der in Deutschland vorkommenden Arten über die Zeit vom Effekt der Standorteigenschaften auf die Arten differenziert werden. Es kann angenommen werden, dass der landschaftsbezogene Unterschied der Standorteigenschaften der Nisthilfen der beiden Studien einen Einfluss auf die vorkommenden Arten hat, denn die beiden Arten, welche in dieser Arbeit in der Nisthilfenumgebung den höchsten Versiegelungsgrad aufwiesen, *Hylaeus hyalinatus* und *Anthidium manicatum*, kamen in der Studie von @tscharntke1998 nicht vor und können als "urbanophile" Arten, also an den städtischen Bereich angepasste Arten, bezeichnet werden. Ein Hinweis darauf, dass die Gartenwollbiene, *Anthidium manicatum*, an die städtische Umgebung angepasst ist, bestätigt auch der Artensteckbrief in @westrich2019, der die Art als Art der Gärten in Dörfern und Städten beschriebt. Auch die Art *Hylaeus hyalinatus* wird von @westrich2019 als snynthrophe Art, also eine im menschlichen Siedlungsbereich vorkommende Art, beschrieben. Einen weiteren Hinweis auf die Anpassung der Garten-Maskenbiene, *Hylaeus hyalinatus*, an den städtischen Bereich gibt der Nachweis der Studie von @vonkonigslow2019 mit Nisthilfenstandorten in Gärten. 
Das Bild der in Siedlungsbereichen vorkommenden Arten, welches diese Arbeit abgibt, kann sich durch die Fortführung des Schulinsektenhausprojektes in den nächsten zwei Jahren durch die Häufigkeit urbanophiler Arten potentiell verdeutlichen, da sich die Arten an den durch das Projekt geschaffenen Standorten mit verfügbaren Nistmöglichkeiten etablieren werden, wie es sich auch in der Studie von @gathmann1999 zeigte.

Sowohl die Artenzahlen der Wildbienen als auch deren Abundanz waren in Nisthilfen, in dessen Umfeld sich ein Insektenhaus befand, höher als in Nisthilfen, in dessen Umfeld sich kein Insektenhaus befand. Ein signifikanter Einfluss konnte jedoch nur für die Artenzahlen beschrieben werden. Dies widerspricht den Beschreibungen eines signifikanten Anstieges der Abundanz bei einer Zunahme der bereitgestellten Nisthilfen von @tscharntke1998 und @gathmann1997. Demnach werden Hautsächlich die beiden Arten *Osmia bicornis* und *O. cornuta* durch Nisthilfen gefördert. Auch dies wiederspricht dem Ergebniss dieser Arbeit, denn es wurde kein Zusammenhang zwischen vorhandenen Insektenhäusern und der Abundanz von *Osmia bicornis* aufgezeigt. Der Unterschied der Ergebnisse der Studien zu dieser Arbeit ist wahrscheinlich durch die unterschiedliche Art der bereitgestellten Nistmöglichkeiten begründet. Die Daten, welche von den Partnern an den Schulen erfasst wurden, bezeichnen bereits bestehende Insektenhäuser die den jeweiligen Partnern bekannt sind. Es ist anzunehmen, dass die Art als auch Entfernung der beschriebenen Insektenhäuser sehr variabel ist und die Modellierung somit eine hohe Unsicherheit beinhaltet. Hinzu kommt, dass es sich bei den erfassten Insektenhäusern potentiell um kommerziell erworbene oder selbstgebaute Insektenhäuser handelt, die sich anders auf Artenzahlen und Abundanzen der Bienen auswirken als standardisierte Nisthilfen [@vonkonigslow2019]. Dass es zur Beanwortung der Fragestellung nach dem Einfluss von vorhandenen Insektenhäusern auf die Wildbienen in Nisthilfen zusätzliche Informationen benötigt wird durch die Empfehlung von @dainese2018 unterschrichen, zur Analyse des Einflusses von Insektenhäusern auf die Abundanz von *Osmia bicornis*  ein Versuchsdesign mit Vorher-Nachher Kotrolle mit mehr als einem Jahr anzuwenden.  
Der Einfluss von vorhandenen Insektenhäusern auf die Artenzahlen der Wildbienen ist deutlicher als der des Versiegelungsgrades auf die Artenzahlen, während sich diese Einflüsse auf die Abundanz invers verhalten. Auf eine Interpretation dieses Ergebnisses wird hier aufgrund der Unsicherheit der Daten nicht eingegangen. Für eine genauere Untersuchung der beschriebenen Zusammenhänge sollten Information über die Art des Insektenhauses sowie dessen Alter und Entfernung von der Nisthilfe miteinbezogen werden.


<!-- Durch Nisthilfen kann das Vorkommen von Hohlraumbesiedlern, also Bienen und Wespen, welche Nisthilfen besiedeln, erhöht werden (Gathmann und Tscharntke 1997 - Bees and wasps in the agricultural landscape: colonization and augmentation in trap nests. Mitteilungen der Deutschen Gesellschaft für Allgemeine und Angewandte Entomologie). Hauptsächlich Osmia bicorns und Osmia cornuta werden gefördert. -->
<!-- Abundanz von Osmia bicornis ist durch die Art der Anbringung der Nisthilfe beeinflusst und die Anzahl verfügbarer Nistplätze  [@everaars2011]   -->
<!-- cornuta bicornis konkurrieren andere Arten aus nach einigen jahren da sie sehr früh die Nester belegen. Also vielleicht vor allem in den Häusern wo viele Nester sind weil in der nähe altes Bienenhaus.   -->

Der Versiegelungsgrad hat im Bereich des Flugradius der Bienen (100m, 250m, 500m) einen negativen Einfluss auf Artenzahl und Abundanz der Wildbienen, als auch auf die Abundanz von *O. bicornis*. Dies wiederspricht den Hypothesen, welche besagen, dass die Artenzahl und Abundanzen bei mittlerem Versiegelungsgrad am höchsten sind. Eine mögliche Erklärung ist eine Fehlinterpretation der Versiegelungsdaten als Urbanisierungsgrad. Die Annahme, dass der mittlere Versiegelungsgrad die Stadtrandbereiche mit vielfältigen Nist- und Futterressourcen beschreibt, während Flächen mit minimaler Versiegelung auf ländliche, von Monokuluren geprägte Gebiete hindeuten, kann hier hinterfragt werden. <!-- dow2000 beschriebt  -->
Da sich die Nisthilfenstandorte hauptsächlich im Umfeld von Schulen befinden, könnte auch angenommen werden, dass es sich bei Flächen mit sehr geringer Versiegelung um parkähnliche Strukturen handelt, welche Futter- und Nistressourcen für Wildbienen bieten und eine artenreiche Bienengemeinschaft beherbergen können [@banaszak-cibicka2018; @darocha-filho2020]. Die Ergebnisse lassen sich durch den Versiegelungsgrad als direkte Ressourcenverfügbarkeit besser erklären, ein hoher Versiegelungsgrad entspricht somit einer Ressourcenknappheit. Dies entspricht der Beobachtung die @ahrne2008 in Schweden an Nisthilfen machte. Ein zunehmender Versiegelungsgrad im Flugradius der Bienen bedeutet eine Abnahme der Ressourcen, welche zu einer Abnahme der Artenzahlen und der Abundanzen der Wildbienen in den Nisthilfen führen. 
<!-- @shochat2006 empfehlen große Relikte natürlicher Habitate innerhalb der städtischen Kerngebiete in zukünftige Forschungen mit einzubeziehen. -->

Die Hypothese des mittleren Versiegelungsgrades als Lebensraum für die höchste Artenvielfalt und Häufigkeit konnte in dieser Arbeit für Bienenartenzahl, Bienenabundanz und Abundanz von *Osmia bicornis* durch den Versiegelungsgrad im weiteren Umfeld beschrieben werden. Dies kann dadurch erklärt werden, dass der Versiegelungsgrad im 1000m sowie 2000m-Radius um die Nisthilfenstandorte die Lage des Standortes innerhalb des städtischen Bereichs und auch die Habitatvernetzung beschreibt und somit der geeignetere Index zur Analyse des Urbanisierungsgrades ist. Maximale Artenzahlen und Abundanzen zeigen sich durch die Modellierungen dieser Arbeit bei einem prozentualen Versiegelungsgrad von $25\% - 35 \%$, welcher etwas geringer ist als der Mittelwert des Versiegelungsgrad aller Nisthilfenstandorte in dieser Arbeit (im 500m-Radius: Mittelwert = 35,3%, Median = 34,7%). Die maximalen Artenzahlen dieser Studie wurden im Vergleich zu den in Frankreich durchgeführten Studien von @fortel2014 (Lyon) und @geslin2016 (Paris) für einem deutlich niedrigeren Versiegelungsgrad modelliert. Die beiden französischen Studien zeigten maximale Artenzahlen bei 50-60% Versiegelter Fläche im 500m-Radius, wobei die Methode der Berechnung der versiegelten Fläche sich von der Methodik dieser Arbeit unterscheidet. Zur Ermittlung der versiegelten Fläche wurde in den Studien von @fortel2014 und @geslin2016 die Landnutzungskategorieen "Straßen", "Gebäude" und "Industrielle Flächen" zusammengeführt. Dass die Vielfalt an Lebensräumen in den Französischen Großstädten Lyon und Paris nicht direkt mit den Lebensräumen in deutschen Städten zu vergleichen ist, stellt eine mögliche Ursache für den Unterschied des Versiegelungsgrades welcher maximale Artenzahlen beschreibt dar. Dies wiederspricht jedoch der Annahme von @mckinney2006, dass Städte sich bezüglich der Artendiversität, die sie beherbergen, überregional gleichen.  
Die für die untersuchten Variablen modellierten Maxima liegen für die Artenzahl bei 30% versigelter Fläche, für die Abundanz bei etwa 25% versiegelter Fläche und für die Abundanz von *Osmia bicornis* bei etwa 35% versiegelter Fläche. Dies kann darauf hindeuten, dass die Rostrote Mauerbiene (*O. bicornis*) besonders gut an die städtische Umgebung angepasst ist. 
<!-- Allerdings sollte hinterfragt werden ob die Genauigkeit der Daten und Modelle diese Aussage zulässt. -->

<!-- abundanz bei mittlerem Versiegelungsgrad: , zanette2005, matteson2008, hernandez2009 -->

- Absatz dazu noch schreiben: Diskussion der best geeigneten Radien zur Beschreibung der Zusammenhänge - Aussage über passenden Radius zur Modellierung der Wildbienen - vergleich zu anderen Studien

Zusätzlich zum Einfluss des Versiegelungsgrades konnte ein Effekt der Landschaftskomplexität ausschließlich auf die Abundanz der Wildbienen aufgezeigt werden.  Dies entspricht den Ergebnissen von @steckel2014, die ebenfalls keinen Effekt der Landschaftssturktur auf die Artenzahl der Bienen, jedoch auf die Abundanz der Bienen erfassten.   
In dieser Arbeit zeigt sich ein negativer Einfluss der Kantenlänge von aneinandergrenzenden Landnutzungsklassen im 500m-Radius und ein positiver Einfluss der Anzahl an Landnutzungklassen im 500m-Radius auf die Abundanz.   
Die aus den Daten der Landnutzungsklassen berechnete Kantenlänge, welche in dieser Arbeit als Index für das Habitatnetzwerk dient, hat sich nicht als zu Interpretation des Habitatnetzewrkes geeignet herausgestellt. Denn die Analyse der verschiedenen beschreibenden Variablen in dieser Arbeit zeigte einen negativen Zusammenhang zwischen Kantendichte und der Landnutzungskategorie "Stadt", in der die Kategorien "Stadtgefüge", "Industrie" und "Gewerbe- und Transiteinheiten" zusammengefasst wurden. Das Umfeld vieler Nisthilfenstandorte war demnach zum Großteil von der Kategorie "Stadt" geprägt, was in den meisten Fällen eine sehr geringen Kantenlänge bedeutet. Die Klasse "Stadt" ist hierbei im Vergleich zu anderen Kategorien, wie beispielsweise landwirtschaftlichen Flächen, in sich viel heterogener.   

Der Aufgezeigte Einfluss der Anzahl an Landnutzungklassen auf die Abundanz der Wildbienen, bestätigt die Hypothese, dass verschiedene Landnutzungsformen in größerem Umfang Futterressourcen und Nistmöglichkeiten für verschiedene Bienenarten bieten, was auch deren Häufigkeit positiv beeinflusst. Allerdings sollte auch dieses Ergebnis aufgrund der Ungenauigkeit der satellitengestützten Landnutzungsklassifizierung, beziehungsweise der Einteilung der Klassen mit Vorsicht betrachtet werden.
Die Landnutzungsklassen sind bezüglich ihrer Eigenschaft relevante Habitateigenschaften für Wildbienen abzubilden je nach Klasse in unterschiedlichem Maße geeignet, denn die Klassen beschreiben die Nutzung durch den Menschen, welche die Habitateigenschaften von Wildbienen nur für ein Teil der Nutzungsformen, z.B. Wald und Ackerland, beschreiben und auch dies mit einer Ungenauigkeit. So kann beispielsweise die Intensivität der Nutzung innerhalb der Kategorie der Weideflächen variieren, was in Studien, die einen Schwerpunkt auf dieser Landnutzungsform haben, im Versuchsdesign integriert wird. Dies wurde auch von @steckel2014 beobachtet, welche die in ihrer Studie untersuchte Landnutzungsklasse der seminatürlichen Habitate je nach Region beurteilen mussten und somit innerhalb der Kategorie gegensätzliche Ergebnisse erfassten.    
Um den genannten Schwächen der Indizes für die Landschaftskomplexität zu entgegnen, sollten für Folgestudien andere Indizes welche die Landnutzung beschreiben in Betracht gezogen werden. 
Eine denkbare Methodik wäre, die ursprünglichen clc-Landnutzungsklassen beizubehalten anstatt sie wie in dieser Arbeit durch Zusammenfassung von Kategorien zu vereinfachen. Die Klassen könnten zusätzlich anhand ihrer jeweiligen potentiellen Habitateigenschaften bewertet wird. Hierzu könnte beispielsweise eine Gewichtung der Klassen anhand der Heterogenität ihrer Habitateigenschaften durchgeführt werden. 
Für weiter Studien ist eine genaue Abwägung nötig, inwiefern sich Landnutzungklassifikationen insbesondere im städtischen Umfeld zu Beschreibung des Lebensraumes von hohlraumnistenden Wildbienen eignen.  
<!-- Denn in anderen Studien ... wurde der Effekt der Landschaftstruktur bereits aufgezeigt. -->


Die Artenzahl der natürlichen Gegenspieler ließ sich ausschließlich durch die Artenzahl ihrer Wirte beschreiben - weder Landnutzung noch Urbanisierung zeigte einen zusätzlichen Effekt. Ein positiven Effekt der Landschaftsdiversität auf die natürlichen Gegenspieler, wie ihn @steffan-dewenter2003a für die natürlichen Gegenspieler von Bienen und Wespen in Nisthilfen beobachten konnten, konnte in dieser Arbeit für die Landschaftskomplexität nicht aufgezeigt werden. Somit gleichen die Ergebnisse dieser Arbeit den Ergebnissen von @holzschuh2010, welche ebenfalls beschreiben, dass die Einflüsse der Landschaft hauptsächlich durch die Wirtsarten auf die natürlichen Gegenspieler  übermittelt werden. Ein potentieller zusätzlicher Einfluss von Landschaft und Urbanisierungsgrad ist dennoch nicht auszuschließen, da er durch die Datengrundlage dieser Arbeit vermutlich nicht dargestellt werden kann. Denn die Parameter welche Landschaft und Urbanisierung beschreiben sind mit einer relativ größeren Unsicherheit behaftet als der Parameter der Artenzahl der Wirte. 
<!--@steffan-dewenter2008: thus the impact of natural enemies on smaller populations (of osmia bicornis) is stronger than on larger ones. -->

Die Abundanz von *Osmia bicornis* wird durch den Versiegelungsgrad als auch durch den Breitengrad beeinflusst. Auch von Anteil an Ackerland und Längengrad kann ein Einfluss auf die Abundanz von *O. bicornis* aufgezeigt werden. 

<!-- Da ländliche Gebiete jedoch auch intensiv genutzte Landwirtschaftliche Flächen beinhalten, was @warren2018 am Konzept des Stadt-Land Gradienten bemängelt haben, wird in dieser Arbeit auch der Anteil an Landwirtschaftlichen Flächen mit einbezogen. - welche jedoch außer bei Osmia bicornis nichts aufzeigen -->

Zusätzlich wurde die Artengemeinschaft untersucht, jedoch konnte statistisch kein Zusammenhang zu Urbanisierung und Landnutzung aufgezeigt werden. Dennoch zeigt die deskriptive Analyse der Artengemeinschaft, dass von den "seltensten" Arten, welche nur in einer Nishilfe des Schulinsektenhausprojektes vorkamen, der Großteil im Umfeld von geringem Versiegelungsgrad vorkamen. Dies entspricht auch den Beobachtungen von @ahrne2008 in Stockholm (Schweden), die in ihrer Studie die meisten einmalig vorkommenden Arten in der ländlichen heterogenen Landschaft erfasste als auch den Ergebnissen von @banaszak-cibicka2018, welche jedoch nicht zwischen hohlraumnistenden Arten und anderen Wildbienen differenzierten.

Mit der Netzwerkanalyse der Wirt-Parasitoid-Beziehungen in dieser Arbeit konnte kein Effekt der Urbanisierung aufgezeigt werden. Der Spezialisierungsgrad der Netzwerke lag unabhängig der Lage des Nisthilfenstandortes bei einem Index H2' von $0.6$. In der Arbeit von  @pereira-peixoto2016 wurden ebenfalls Wirt-Parasitoid-Beziehungen im Stadt-Land-Kontext untersucht, und keinen Einfluss des Urbanisierungsgrades festgestellt. Auch der allgemeine Spezialisierungsgrad wurde mit einem Wert von $H2' = 0.62$ erfasst - wobei Wespenarten in die Analyse miteinbezogen waren. 
Allerdings konnten hier signifikante Unterschiede zwischen Isolierten Habitaten (Land und Stadt) und aneinandergrenzenden Habitaten verschiedener Landschaftstypen (Stadtrandbereich) aufgezeigt werden, während in dieser Studie kein Effekt der Landschaftstruktur aufgezeigt werden konnte. Das Forschungsdesign der Studie von  @pereira-peixoto2016 mit der gezielten Auswahl der Standorte in der Landschaft ist genauer an die Fragestellung angepasst, als die in dieser Arbeit verwendete Methodik zur Landschaftstruktur. 


Es ist anzunehmen, dass sich die Ergebnisse zum Einfluss von Landnutzung und Urbanisierung auf hohlraumnistende Wildbienen und ihre Gegenspieler durch das mehrjährige Monitoring noch verdeutlichen und potentiell weitere Zusammenhänge aufgezeigt werden können. Denn es wurde bereits in verschiedenen Studien aufgezeit, dass es bei Bestäubern eine hohe Variabilität zwischen verschiedenen Jahren gibt [@burkle2011]. Dies gilt insbesondere dann, wenn Interaktionen im Ökosystem aus dem Gleichgewicht geraten.


<!-- what the results show -->


<!-- what the results mean (interpretation) for the question or controversy which motivated the experiment -->

<!-- explain our new understanding of the problem after taking your results into consideration. -->


<!-- explained your experiment's significance for scientific knowledge of your subject as you summarized it in the Introduction. -->

<!-- --------------- -->

<!-- Given your conclusions, what is our new understanding of the problem you investigated and outlined in the Introduction? If warranted, what would be the next step in your study, e.g., what experiments would you do next? -->


<!-- - weitere Punkte die ich noch diskutieren könnte: -->
<!--   - uncertainty of data: @guisan2017: p 103: guisan and Hofer 2003 -->
<!--   - uncertainty in species distribution, spacial uncertainty (angegebene Koordinaten der Schulen) -->
<!--   - Modellselektion: kritisch mit stepAIC, AIC und anova suchen das beste aus, da jedoch in den geodaten eine potentiell große Unsicherheit besteht, könnte für weitere untersuchungen auch eine andere Methode in Betracht gezogen werden, wie zum Beispiel "enseble modeling" [@burnham2002h; @guisan2017 p. 225]. Hierdurch kann wiederum auf die (räumliche) Genauigkeit der Daten rückgeschlossen werden. -->
<!-- <!-- Methodenkritik: rauschen in den Daten - anbringung der Nisthilfen - citizen science , stepAIC ist ein kack, ungenauigkeit der Satellitendaten vs. Artenzahl der Wirte bei Parasitoiden (Host ist nicht uniformverteilt- man müsste ihn transformieren)--> 
<!--   - Die in dieser Arbeit verwendeten Daten des Versiegelungsgrades im 500m-Radius, als auch die nicht im Bezug auf die Fragestellung ausgewählten Standorte der Nisthilfen sind zur Beantwortung der Fragestellung nicht zielführend. Es ist zu vermuten, das die Daten eine zu hohe Ungenauigkeit haben, als auch, dass sie die Effekte weiterer unbekannter Variablen abbilden. -->



<!-- ######### -->
<!-- Die Abundanz (Häufigkeit) einzelner Wildbienenarten ist, bedingt durch die natürliche Dynamik der Populationen, zeitlich und räumlich sehr variabel [@williams2001]. Die Artenzusammensetzung der Wildbienenfauna ist zeitlich weniger variabel und zeigt im Verlauf mehrerer Jahre Artenverschiebungen [@williams2001].  -->
<!-- - how difficult generalisations across different taxonomic groups can be [@ewers2005]. -->
<!-- - As bees show different, often species-specific pollen preferences to provision their nests, their abundances can probably only be explained in the presence of more detailed knowledge of their foraging habitats (Cane 2001, Habitat fragmentation and native bees: a premature verdict). <!-- Quelle als odt?! --> 

<!-- Lebensräume im städischen Gebiet unterliegen einem generellen Wandel, z.B durch Nachverdichtung, Abriss und Neubau von Häusern, Straßen, Radwegen, Tramlinien, usw.. In Privatgärten kann es zu Strukturveränderungen der Kleinstrukturen kommen durch das Anlegen von Steingärten oder sterilen Rasen. Auf der anderen Seite wurden in den letzten Jahren, insbesondere durch das Medienecho auf das "Insektensterben" in Städten vielerlei Maßnahmen zum Naturschutz umgesetzt. Dazu zählen z.B. ein Trend von Insektenhäusern in privaten Gärten aber auch Blühstreifen und Wiesen mit geringerem Mahdrhythmus auf städtischen Grünflächen oder Steinhaufen, Trockenmauern etc. als Teil von Ausgleichsmaßnahmen.  -->


<!-- Artenvorkommen kann auch von einer ehemalige Landnutzung kommen [@do2014]. -->

<!-- @pickett2001 claimed that urban gradients offer a very effective framework for studying impacts of urbanisation on invertebrates because they can capture a wide variety of urban effects. @new2015 s. 36 -->



<!-- They may result from (1) localised direct habitat degradation or loss or from (2) wider changes in regional land use, together imposing two rather different scales for evaluation. Both may be infl uenced further by progressive influences of alien species as conditions continue to change [@new2015]. -->



<!-- @geslin2016: In general, urbanization appears to act as a filter for bee communities by promoting large‐bodied and aboveground‐nesting species and inhibiting small‐bodied and ground‐nesting bees in urban matrices (Banaszak‐Cibicka and Żmihorski 2012; Geslin et al. 2013).  -->


