# Abstract {-}

Wild bees have complex habitat requirements due to their specialization on particular food resources, nesting materials & sites. One of the reasons for the decline of wild bee species in Germany is the anthropogenic change of their habitats. In this study, I investigated how land use and urbanization affect cavity-nesting wild bees and their natural enemies. Through a nationwide survey of wild bees in trap nests, this work contributed to the understanding of wild bee habitat conditions and allowed an assessment of habitat quality with a focus on urban areas.        
For this purpose, all bee species and those of their natural enemies, as well as their abundance in each case, were recorded from 259 trap nests installed in 2019.
Satellite-based classifications of land use formed the basis for quantifying land use, the degree of imperviousness calculated from satellite data formed the basis for quantifying urbanization. Two indices of landscape complexity were calculated from the land use classes.
With these data, the influence of land use and urbanization on species number and abundance of wild bees, species number of natural enemies and abundance of the most common bee species *Osmia bicornis* could be investigated. Furthermore, the extent to which urbanization affects the species community in trap nests and host-parasitoid interactions was analyzed. Climate data and data on existing nesting aids were considered in all analyses.    
A total of 32 bee species were detected in the trap nests. A tendency of species shifts along the urban-rural gradient from species adapted to urban areas to species adapted to rural areas was revealed. However, this tendency could not be statistically proven.
The maximum species number and abundance of wild bees, as well as the maximum abundance of *Osmia bicornis* was recorded at a medium level of imperviousness (25-35% of the area is sealed) in the vicinity of the trap nest locations.
This effect was described by the degree of impervious surface in the surrounding area of 500m, 1000m and 2000m. 
Landscape complexity had a positive influence on the abundance of wild bees.
On the other hand, the number of species of natural enemies could be described only by the number of species of wild bees. 
Relationships between landscape complexity and variables other than wild bee abundance could not be shown. The main reason for this is that the landscape complexity indices used turned out to be poorly suited to represent wild bee habitats. Therefore, other landscape indices to describe landscape complexity should be considered for future studies.  
Describing the degree of urbanization by the degree of impervious surface within a 500m-2000m radius led to the following conclusion: wild bees are influenced by direct resource availability on the one hand and habitat connectivity and localization within the city on the other. Urban fringe areas can host diverse cavity-nesting bee communities.
