# Zusammenfassung {-}
<!-- In dieser Arbeit wird die Artenzusammensetzung der Bienen in Nisthilfen entlang eines Stadt-Land-Gradienten untersucht. Anhand der Analyse von Artenzusammensetzung und Parasitierung soll die Habitatqualität im Siedlungsbereich bewertet werden. Die für diese Arbeit analysierten Nishilfen sind Teil des Projekt "Schulinsektenhaus". -->
Wildbienen haben durch ihre Spezialisierung auf bestimmte Nahrungsressourcen, Nistmaterialien & -plätze komplexe Ansprüche an ihren Lebensraum. Einer der Gründe für den Rückgang an Wildbienenarten in Deutschland ist die anthropogene Veränderung ihrer Lebensräume. In dieser Arbeit wurde der Fragestellung nachgegangen, inwiefern sich Landnutzung und Urbanisierung auf hohlraumnistende Wildbienen und deren Gegenspieler auswirken. Durch eine deutschlandweite Erfassung von Wildbienen in Nisthilfen trug diese Arbeit zum Verständnis der Lebensbedingungen von Wildbienen bei und ermöglichte eine Bewertung der Habitatqualität mit einem Fokus auf den städtischen Bereich.      
Dafür wurden aus 259 Nisthilfen, die im Jahr 2019 aufgestellt waren, alle Bienenarten und jene ihrer natürlichen Gegenspieler sowie jeweils ihre Häufigkeit (Abundanz) erfasst. 
Satellitendaten bildeten die Basis zur Quantifizierung von Landnutzung und Urbanisierung: für Ersteres satellitenbasierte Klassifikationen von Landnutzungsklassen, für Letzteres der aus Satellitendaten berechnete Versiegelungsgrad. Aus den Landnutzungsklassen wurden zwei Indizes für die Landschaftskomplexität berechnet.
Mit diesen Daten konnte der Einfluss von Landnutzung und Urbanisierung auf Artenzahl und Abundanz der Wildbienen, Artenzahl der natürlichen Gegenspieler und Abundanz der häufigsten Bienenart *Osmia bicornis* untersucht werden. Des Weiteren wurde analysiert, inwieweit die Urbanisierung sich auf die Artengemeinschaft in den Nisthilfen und die Wirt-Parasitoid-Interaktionen auswirkt. Bei allen Analysen wurden Klimadaten und Daten zu bestehenden Insektenhäusern berücksichtigt.  
In den Nisthilfen konnten insgesamt 32 Bienenarten nachgewiesen werden. Es zeigte sich eine Tendenz von Artverschiebungen entlang des Stadt-Land-Gradienten von Arten, die an den städtischen Raum angepasst sind, hin zu Arten des ländlichen Raumes. Diese Tendenz konnte allerdings nicht statistisch belegt werden.
Die maximale Artenzahl und Abundanz der Wildbienen, sowie die maximale Abundanz von *Osmia bicornis* wurde bei einem mittleren Versiegelungsgrad (25-35% der Fläche sind versiegelt) im Umfeld der Nisthilfenstandorte erfasst.
Dieser Effekt wurde durch den Versiegelungsgrad im Umfeld von 500m, 1000m und 2000m beschrieben. 
Einen positiven Einfluss auf die Abundanz der Wildbienen hat auch die Landschaftskomplexität.
Dahingegen konnte die Artenzahl der natürlichen Gegenspieler ausschließlich durch die Artenzahl der Wildbienen beschrieben werden. 
Zusammenhänge zwischen der Landschaftskomplexität und anderen Variablen als der Abundanz der Wildbienen konnten nicht aufgezeigt werden. Hauptgrund hierfür ist, dass sich die verwendeten Landschaftskomplexitäts-Indizes als wenig geeignet herausstellten, um Wildbienenhabitate abzubilden. Für zukünftige Studien sind daher andere Landschaftsindizes zur Beschreibung der Landschaftskomplexität zu erwägen.
Die Beschreibung des Urbanisierungsgrades durch den Versiegelungsgrad in einem Radius von 500m-2000m führte zu folgender Schlussfolgerung: Wildbienen werden sowohl von der direkten Ressourcenverfügbarkeit als auch von der Habitatvernetzung und Lokalisierung innerhalb der Stadt beeinflusst. Stadtrandbereiche können vielfältige hohlraumnistende Bienengemeinschaften beherbergen.


